---
title: "final_lda"
author: "Lynette Pan"
date: "12/13/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(mice)
library(gee)
library(lme4)


frmgham = 
  read.csv2("frmgham2.csv", sep = ",", na.strings=c("","NA")) %>% 
  clean_names() %>% select(cursmoke, everything()) %>% 
  mutate(sex = as.factor(sex),
         bpmeds = as.factor(bpmeds),
         educ = as.factor(educ),
         diabetes = as.factor(diabetes),
         prevap = as.factor(prevap),
         prevchd = as.factor(prevchd),
         prevmi = as.factor(prevmi),
         prevstrk = as.factor(prevstrk),
         prevhyp = as.factor(prevhyp),
         sysbp = as.numeric(levels(sysbp))[sysbp],
         diabp = as.numeric(as.character(diabp)),
         bmi = as.numeric(as.character(bmi))) %>% 
  as.tibble()

## created age category variable (age_ctg)
frmgham =
  frmgham %>% 
  mutate(
      age_ctg = case_when(
      age < 35 ~ "35-",  
      age %in% 35:44 ~ "35-44",
      age %in% 45:54 ~ "45-54",
      age %in% 55:64 ~ "55-64",
      age %in% 65:74 ~ "65-74",
      age >= 75 ~ "75+"
    ),
    age_ctg = fct_relevel(age_ctg, "35-")) 

## created sysbp category variable (sysbp_ctg)
### According to the new guideline from american heart association
### https://www.ahajournals.org/doi/10.1161/HYP.0000000000000065
frmgham =
  frmgham %>% 
  mutate(
      sysbp_ctg = case_when(
      sysbp < 120 ~ "normal",  
      (sysbp >= 120 & sysbp < 130) ~ "elevated",
      (sysbp >= 130 & sysbp < 140) ~ "stage1",
      (sysbp >= 140 & sysbp <= 180) ~ "stage2",
      sysbp > 180 ~ "crisis"
    ),
    sysbp_ctg = fct_relevel(sysbp_ctg, "normal")) 

## created sysbp category variable (diabp_ctg)
### According to the new guideline from american heart association
### https://www.ahajournals.org/doi/10.1161/HYP.0000000000000065
frmgham =
  frmgham %>% 
  mutate(
      diabp_ctg = case_when(
      diabp < 80 ~ "normal and elevated",  
      (diabp >= 80 & diabp < 90) ~ "stage1",
      (diabp >= 90 & diabp <= 120 ) ~ "stage2",
      diabp > 120 ~ "crisis"
      ),
    diabp_ctg = fct_relevel(diabp_ctg, "normal and elevated")) 

```

(3)The relationship between current smoking status and serum total cholesterol. Again, while answering these questions, please account for any confounders that you have evidence may impact these relationships. 


```{r}
frmgham %>% 
  ggplot(., aes(x=cursmoke, y=totchol)) +
    geom_bar(stat="identity") +ggtitle("Unadjusted relationship between current smoking status and serum total cholesterol")


frmgham %>% 
  ggplot(., aes(x=as.factor(cursmoke), y=totchol)) +
  geom_boxplot() +ggtitle("Serum total cholesterol by current smoking status, Boxplot")


frmgham %>% 
  ggplot(., aes(x=as.factor(cursmoke), y=totchol)) +
  geom_violin(aes(fill = as.factor(cursmoke))) +ggtitle("Serum total cholesterol by current smoking status, Violin")
#https://medlineplus.gov/cholesterollevelswhatyouneedtoknow.html
#categorized totchol based on link above

frmgham=frmgham %>% 
  mutate(totchol_ctg= ifelse(age<=19 & totchol<170,0,
                             ifelse(age>19&totchol %in% c(125, 200), 0,1)))
table(frmgham$totchol_ctg)
# 124 normal total chol 
# 11503 abnormal total chol


a=frmgham %>% 
  filter(!is.na(totchol)) %>% 
  filter(period==3)
range(a$totchol)
```


## Finding confounders


```{r}
library(nlme)
frmgham= frmgham %>% 
  mutate(bmi=as.numeric(as.character(bmi))) %>% 
  mutate(bmi_cat = ifelse(bmi<18.5,0,ifelse(bmi %in% c(18.5,24.9), 1, ifelse(bmi %in% c(25, 29.9),2, 3))))

a=as.data.frame(lapply(frmgham[,c("cursmoke","age","sex","prevchd")], as.numeric))
cor(a)
totchol1 <- 
  gls(totchol ~ as.factor(cursmoke)*period+sex+bmi+age, 
      data = frmgham,na.action=na.omit, corr = corCompSymm(,form= ~ 1 | randid) )

totchol <- 
  gls(totchol ~ as.factor(cursmoke), data = frmgham,na.action=na.omit)
totchol3=lmer(totchol ~ as.factor(cursmoke)+age+sex+prevchd+(1|randid),
              data=frmgham)

totchol4=lmer(totchol ~ as.factor(cursmoke)*age+sex+prevchd+(as.factor(cursmoke)|randid),
              data=frmgham)

totchol5=lmer(totchol ~ as.factor(cursmoke)+age+sex+prevchd+bmi+(1|randid),
              data=frmgham)
totchol6=lmer(totchol ~ as.factor(cursmoke)+age+sex+prevchd+bmi+(1|randid),
              data=frmgham)

frmgham=frmgham %>% 
  mutate(period = period-1)

totchol7=lmer(totchol ~ as.factor(cursmoke)*sex+bmi+age+prevchd+(1|randid),
              data=frmgham)
totchol8=lmer(totchol ~ as.factor(cursmoke)*sex+bmi+age+(1|randid),
              data=frmgham)
totchol9=lmer(totchol ~ as.factor(cursmoke)+sex+bmi+age+(1|randid),
              data=frmgham)
totchol11=lmer(totchol ~ as.factor(cursmoke)*as.factor(period)+sex+bmi+age+(1|randid),
              data=frmgham)
totchol10=lmer(totchol ~ as.factor(cursmoke)+as.factor(period)+sex+bmi+age+(1|randid),
              data=frmgham)

totchol12=lmer(totchol ~ as.factor(cursmoke)+as.factor(period)+bmi+age+(1|randid),
              data=frmgham)
totchol13=lmer(totchol ~ as.factor(cursmoke)*sex+bmi+age+prevstrk+prevchd+(1|randid),
              data=frmgham)

#final model
totchol15=lmer(totchol ~ as.factor(cursmoke)*sex+bmi+age+sysbp+(1|randid),
              data=frmgham)
AIC(totchol15)
totchol14=lmer(totchol ~ as.factor(cursmoke)+sex+hdlc+bmi+age+(1|randid),
              data=frmgham)
frmgham %>% 
  mutate(sex = ifelse(sex == 1, "male", "women")) %>%
  select(randid, cursmoke, sex,totchol) %>% 
  na.omit() %>% 
  group_by(cursmoke, sex) %>% 
  summarise(p_cursmoke = sum(cursmoke)/n(),
            lower_CI = prop.test(sum(cursmoke), n())$conf.int[1],
            upper_CI = prop.test(sum(cursmoke), n())$conf.int[2]) %>%
  ggplot(aes(x = age_ctg, y = p_cursmoke, color = sex, group = sex)) +
  geom_errorbar(aes(ymin = lower_CI, ymax = upper_CI), width = .1) +
  geom_line() +
  labs(title = "Relationship between categorized age and smoking status by sex",
       x = "Age",
       y = "Probability of current smoking")


# AIC(totchol10)
# summary(totchol10)
# summary(totchol11)
# anova(totchol13,totchol14)
# test the significance of random effect
#sig_ranef=RLRsim::exactRLRT(totchol13, seed=1)

# pot_conf <- names(frmgham)[-c(1,2,4)]
# pot_conf <- pot_conf[-c(grep("time", pot_conf), grep("death", pot_conf))]
# 
# conf_det <- vector("list", length = length(pot_conf))
# names(conf_det) <- pot_conf
# 
# 
# 
# for (conf in pot_conf) {
# 
#  data <- cbind(frmgham[,c("totchol","cursmoke")], frmgham[,conf])
#  try(fit_gee <- gls(totchol ~ .,
#      data = data,
#      ,na.action=na.omit))
# 
#  result <- tibble(
#    variable = c("totchol"),
#    OR =
#      exp(coef(summary(totchol))[2,1]),
#    lower_CI  =
#      exp(coef(summary(totchol))[2,1] - 1.96*(coef(summary(totchol))[2,3])),
#    upper_CI =
#      exp(coef(summary(totchol))[2,1] + 1.96*(coef(summary(totchol))[2,3])),
#    potconf_OR =
#      exp(coef(summary(fit_gee))[2,1]),
#    confounder =
#      if_else((potconf_OR >= lower_CI & potconf_OR <= upper_CI), FALSE, TRUE)
#  )
# 
#  conf_det[[conf]] <- result
# }
# 
# map(conf_det, knitr::kable, digits = 3)
```


##visualize the relationship between totchol and cursmoke by each confounding variable:

```{r}

frmgham %>%
  mutate(cursmoke=as.factor(cursmoke)) %>% 
  group_by(cursmoke) %>%
  ggplot(.)+  
  geom_boxplot(aes(x=cursmoke, y=totchol)) +
  ggtitle("Totochol by smoking status, boxplot")


frmgham %>%
  mutate(cursmoke=as.factor(cursmoke)) %>% 
  group_by(cursmoke, sex) %>%
  summarise(
    n=n(),
    mean=mean(totchol, na.rm=T),
    sd=sd(totchol, na.rm=T)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


ggplot(plot_dt)+
  geom_bar(aes(x=cursmoke, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=cursmoke, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=0.75) +
  ggtitle("Mean totochol by gender")+facet_wrap(~sex)


frmgham %>%
  mutate(cursmoke=as.factor(cursmoke)) %>% 
  group_by(cursmoke, prevchd) %>%
  summarise(
    n=n(),
    mean=mean(totchol, na.rm=T),
    sd=sd(totchol, na.rm=T)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1)) %>% 
  ggplot(.)+
  geom_bar(aes(x=cursmoke, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=cursmoke, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("Mean totochol by prevalence of coronary heart disease ")+facet_wrap(~prevchd)

frmgham %>%
  mutate(cursmoke=as.factor(cursmoke)) %>% 
  group_by(cursmoke, age_ctg) %>%
  summarise(
    n=n(),
    mean=mean(totchol, na.rm=T),
    sd=sd(totchol, na.rm=T)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1)) %>% 
  ggplot(.)+
  geom_bar(aes(x=cursmoke, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=cursmoke, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("Mean totochol by age category")+facet_wrap(~age_ctg)



frmgham %>%
  mutate(cursmoke=as.factor(cursmoke)) %>% 
  group_by(cursmoke, bmi_cat) %>%
  summarise(
    n=n(),
    mean=mean(totchol, na.rm=T),
    sd=sd(totchol, na.rm=T)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1)) %>% 
  ggplot(.)+
  geom_bar(aes(x=cursmoke, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=cursmoke, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("Mean totochol by BMI category")+facet_wrap(~bmi_cat)

```



## bootstrap for confidence interval


```{r}
b_par<-bootMer(x=totchol15,FUN=fixef,nsim=200)
a=boot::boot.ci(b_par,type="basic",index=2)
a$basic[1,4]+b$basic[1,4]
a$basic[1,5]+b$basic[1,5]

b=boot::boot.ci(b_par,type="basic",index=7)
b
fixef(totchol15)
```


